/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package stok;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.ArrayList;

public class PanelManageJenisJenisBarang extends javax.swing.JPanel {
    
    Koneksi koneksi = new Koneksi();

    private DefaultTableModel model;

    // method untuk membuat id otomatis
    private void autonumber() {
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            String sql = "SELECT MAX(id_jenis_jenis) as jumlah_id FROM jenis_dari_jenis";
            ResultSet r = s.executeQuery(sql);
            if (r.next()) {
                String id_jenis = r.getString("jumlah_id");
                int no = Integer.parseInt(id_jenis) + 1;
                String NO = Integer.toString(no);
                txtIDJenisJenisBarang.setText(NO);
            } else {
                txtIDJenisJenisBarang.setText("1");
            }
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println("autonumber error");
        }
    }

    public void clear() {
        txtIDJenisJenisBarang.setText("");
        txtJenisJenisBarang.setText("");
    }

    private void loadData() {
        String id_jenis_barang;
        ArrayList<String> item_jenis_barang = new ArrayList<String>();
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM jenis_dari_jenis";
            ResultSet r = s.executeQuery(sql);
            
            Connection c1 = Koneksi.getKoneksi();
            Statement s1 = c1.createStatement();
            String sql1;
            ResultSet r1;

            while (r.next()) {
                Object[] o = new Object[3];
                o[0] = r.getString("id_jenis_jenis");
                o[1] = r.getString("jenis_jenis");
                id_jenis_barang = r.getString("id_jenis_barang");

                // set tabel jenis dari jenis barang
                sql1 = "SELECT * FROM jenis_barang WHERE id_jenis_barang = '" + id_jenis_barang + "'";
                r1 = s1.executeQuery(sql1);
                while (r1.next()) {
                    o[2] = r1.getString("jenis_barang");
                }
                
                model.addRow(o);
            }
            
            // jenis barang
            txtIDJenisBarang.removeAllItems();
            sql = "SELECT * FROM jenis_barang";
            r = s.executeQuery(sql);
            while (r.next()) {
                item_jenis_barang.add(r.getString("jenis_barang"));
            }
            for (int i = 0; i < item_jenis_barang.size(); i++) {
                txtIDJenisBarang.addItem(item_jenis_barang.get(i));
            }
            
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * Creates new form Home
     */
    public PanelManageJenisJenisBarang() {
        initComponents();
        
        txtIDJenisJenisBarang.setEnabled(false);

        model = new DefaultTableModel();

        jTable1.setModel(model);

        model.addColumn("ID");
        model.addColumn("Jenis Jenis Barang");
        model.addColumn("Jenis Barang");
        loadData();
        autonumber();
    }
    
    private String getIDJenisBarang(String jenis){
        String id_jenis_barang = "";
        try {
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();

            String sql = "SELECT * FROM jenis_barang WHERE jenis_barang = '" + jenis + "'";
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {
                id_jenis_barang = r.getString("id_jenis_barang");
            }
            
            r.close();
            s.close();
        } catch (SQLException e) {
            System.out.println(e);
        }
        return id_jenis_barang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIDJenisJenisBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();
        txtJenisJenisBarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtIDJenisBarang = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCariBarang = new javax.swing.JTextField();

        setBackground(new java.awt.Color(20, 195, 142));
        setMinimumSize(new java.awt.Dimension(100, 100));

        jPanel1.setBackground(new java.awt.Color(20, 195, 142));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setText("MANAGE JENIS DARI BARANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(389, 389, 389))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        jLabel2.setText("ID Jenis");

        txtIDJenisJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDJenisJenisBarangActionPerformed(evt);
            }
        });

        jLabel4.setText("Jenis Dari Jenis Barang");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        txtJenisJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJenisJenisBarangActionPerformed(evt);
            }
        });

        jLabel5.setText("Jenis Barang");

        jLabel3.setText("Cari Barang");

        txtCariBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariBarangKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIDJenisJenisBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txtIDJenisBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtJenisJenisBarang))
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBatal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsert)
                                .addGap(30, 30, 30)
                                .addComponent(btnHapus)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIDJenisJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInsert)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(jLabel4)
                    .addComponent(txtJenisJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtIDJenisBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCariBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDJenisJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDJenisJenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDJenisJenisBarangActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }

        String id = (String) model.getValueAt(i, 0);
        txtIDJenisJenisBarang.setText(id);
        String jenis = (String) model.getValueAt(i, 1);
        txtJenisJenisBarang.setText(jenis);
        String jenis_barang = (String) model.getValueAt(i, 2);
        txtIDJenisBarang.setSelectedItem(jenis_barang);
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        String id = txtIDJenisJenisBarang.getText();
        String jenis_jenis_barang = txtJenisJenisBarang.getText();
        String jenis_barang = (String) txtIDJenisBarang.getSelectedItem();
        
        String id_jenis_barang = getIDJenisBarang(jenis_barang);

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "INSERT INTO jenis_dari_jenis values (?, ?, ?)";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.setString(2, jenis_jenis_barang);
            p.setString(3, id_jenis_barang);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Tersimpan");
            clear();
            loadData();
            autonumber();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id = txtIDJenisJenisBarang.getText();
        String jenis_jenis_barang = txtJenisJenisBarang.getText();
        
        String jenis_barang = (String) txtIDJenisBarang.getSelectedItem();
        String id_jenis_barang = getIDJenisBarang(jenis_barang);

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "UPDATE jenis_dari_jenis SET jenis_jenis = ?, id_jenis_barang = ? WHERE id_jenis_jenis = '" + id + "'";
            PreparedStatement p = c.prepareStatement(sql);

            p.setString(1, jenis_jenis_barang);
            p.setString(2, id_jenis_barang);

            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Terubah");
            clear();
            loadData();
            autonumber();
        } catch (SQLException e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        String id = txtIDJenisJenisBarang.getText();
        String jenis_barang = txtJenisJenisBarang.getText();

        try {
            Connection c = Koneksi.getKoneksi();
            String sql = "DELETE FROM jenis_dari_jenis WHERE id_jenis_jenis = ?";
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
            JOptionPane.showMessageDialog(null, "Data Terhapus");
            
            clear();
            loadData();
            autonumber();
        } catch (SQLException e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        clear();
        autonumber();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void txtJenisJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJenisJenisBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJenisJenisBarangActionPerformed

    private void txtCariBarangKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariBarangKeyTyped
        // TODO add your handling code here:
        String id_jenis_barang;
        
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        
        if(txtCariBarang.getText().length() == 0){
            try {
                Connection c = Koneksi.getKoneksi();
                Statement s = c.createStatement();

                String sql = "SELECT * FROM jenis_dari_jenis";
                ResultSet r = s.executeQuery(sql);

                Connection c1 = Koneksi.getKoneksi();
                Statement s1 = c1.createStatement();
                String sql1;
                ResultSet r1;

                while (r.next()) {
                    Object[] o = new Object[3];
                    o[0] = r.getString("id_jenis_jenis");
                    o[1] = r.getString("jenis_jenis");
                    id_jenis_barang = r.getString("id_jenis_barang");

                    // set tabel jenis dari jenis barang
                    sql1 = "SELECT * FROM jenis_barang WHERE id_jenis_barang = '" + id_jenis_barang + "'";
                    r1 = s1.executeQuery(sql1);
                    while (r1.next()) {
                        o[2] = r1.getString("jenis_barang");
                    }

                    model.addRow(o);
                }

                r.close();
                s.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        } else {
            try {
                Connection c = Koneksi.getKoneksi();
                Statement s = c.createStatement();

                String sql = "SELECT * FROM jenis_dari_jenis WHERE id_jenis_jenis like '%" + txtCariBarang.getText() + "%' OR jenis_jenis like '%" + txtCariBarang.getText() + "%' OR id_jenis_barang like '%" + txtCariBarang.getText() + "%'";
                ResultSet r = s.executeQuery(sql);

                Connection c1 = Koneksi.getKoneksi();
                Statement s1 = c1.createStatement();
                String sql1;
                ResultSet r1;

                while (r.next()) {
                    Object[] o = new Object[3];
                    o[0] = r.getString("id_jenis_jenis");
                    o[1] = r.getString("jenis_jenis");
                    id_jenis_barang = r.getString("id_jenis_barang");

                    // set tabel jenis dari jenis barang
                    sql1 = "SELECT * FROM jenis_barang WHERE id_jenis_barang = '" + id_jenis_barang + "'";
                    r1 = s1.executeQuery(sql1);
                    while (r1.next()) {
                        o[2] = r1.getString("jenis_barang");
                    }

                    model.addRow(o);
                }

                r.close();
                s.close();
            } catch (SQLException e) {
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_txtCariBarangKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCariBarang;
    private javax.swing.JComboBox<String> txtIDJenisBarang;
    private javax.swing.JTextField txtIDJenisJenisBarang;
    private javax.swing.JTextField txtJenisJenisBarang;
    // End of variables declaration//GEN-END:variables
}
