/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Main.stok;

public class FrameMainStokBarang extends javax.swing.JFrame {
    
    PanelTambahBarang panelInsertBarang;
    PanelManageJenisBarang panelManageJenisBarang;
    PanelManageSatuan panelManageSatuan;
    PanelManageJenisJenisBarang panelManageJenisJenisBarang;
    PanelManageBarang panelManageBarang;
    PanelLaporanBarang panelLaporanBarang;

    /**
     * Creates new form MainBarang
     */
    public FrameMainStokBarang() {
        initComponents();
        
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelInsertBarang = new PanelTambahBarang();
        
        PanelContent.add(panelInsertBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelUtama = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        btnInsert = new javax.swing.JButton();
        btnManageBarang = new javax.swing.JButton();
        btnManageJenisBarang = new javax.swing.JButton();
        btnManageSatuan = new javax.swing.JButton();
        btnManageJenisBarang1 = new javax.swing.JButton();
        btnManageSatuan1 = new javax.swing.JButton();
        PanelContent = new javax.swing.JPanel();
        jPanelHome = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1048, 598));

        PanelUtama.setBackground(new java.awt.Color(153, 153, 153));

        PanelMenu.setBackground(new java.awt.Color(20, 195, 142));

        btnInsert.setText("Insert Barang");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnManageBarang.setText("Manage Barang");
        btnManageBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageBarangActionPerformed(evt);
            }
        });

        btnManageJenisBarang.setText("Manage Jenis Barang");
        btnManageJenisBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageJenisBarangActionPerformed(evt);
            }
        });

        btnManageSatuan.setText("Manage Satuan");
        btnManageSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSatuanActionPerformed(evt);
            }
        });

        btnManageJenisBarang1.setText("Manage Jenis-Jenis Barang");
        btnManageJenisBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageJenisBarang1ActionPerformed(evt);
            }
        });

        btnManageSatuan1.setText("Laporan");
        btnManageSatuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageSatuan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMenuLayout = new javax.swing.GroupLayout(PanelMenu);
        PanelMenu.setLayout(PanelMenuLayout);
        PanelMenuLayout.setHorizontalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManageJenisBarang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageJenisBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageSatuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageSatuan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        PanelMenuLayout.setVerticalGroup(
            PanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMenuLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(btnInsert)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageJenisBarang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageJenisBarang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageSatuan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnManageSatuan1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PanelContent.setBackground(new java.awt.Color(0, 153, 102));
        PanelContent.setLayout(new java.awt.CardLayout());

        jPanelHome.setBackground(new java.awt.Color(20, 195, 142));

        javax.swing.GroupLayout jPanelHomeLayout = new javax.swing.GroupLayout(jPanelHome);
        jPanelHome.setLayout(jPanelHomeLayout);
        jPanelHomeLayout.setHorizontalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 842, Short.MAX_VALUE)
        );
        jPanelHomeLayout.setVerticalGroup(
            jPanelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 604, Short.MAX_VALUE)
        );

        PanelContent.add(jPanelHome, "card2");

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addComponent(PanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelContent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageJenisBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageJenisBarangActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelManageJenisBarang = new PanelManageJenisBarang();
        
        PanelContent.add(panelManageJenisBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnManageJenisBarangActionPerformed

    private void btnManageSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSatuanActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelManageSatuan = new PanelManageSatuan();
        
        PanelContent.add(panelManageSatuan);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnManageSatuanActionPerformed

    private void btnManageJenisBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageJenisBarang1ActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelManageJenisJenisBarang = new PanelManageJenisJenisBarang();
        
        PanelContent.add(panelManageJenisJenisBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnManageJenisBarang1ActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelInsertBarang = new PanelTambahBarang();
        
        PanelContent.add(panelInsertBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnManageBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageBarangActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelManageBarang = new PanelManageBarang();
        
        PanelContent.add(panelManageBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnManageBarangActionPerformed

    private void btnManageSatuan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageSatuan1ActionPerformed
        // TODO add your handling code here:
        PanelContent.removeAll();
        PanelContent.repaint();
        PanelContent.revalidate();
        
        // add
        panelLaporanBarang = new PanelLaporanBarang();
        
        PanelContent.add(panelLaporanBarang);
        PanelContent.repaint();
        PanelContent.revalidate();
    }//GEN-LAST:event_btnManageSatuan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMainStokBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMainStokBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMainStokBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMainStokBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameMainStokBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelContent;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnManageBarang;
    private javax.swing.JButton btnManageJenisBarang;
    private javax.swing.JButton btnManageJenisBarang1;
    private javax.swing.JButton btnManageSatuan;
    private javax.swing.JButton btnManageSatuan1;
    private javax.swing.JPanel jPanelHome;
    // End of variables declaration//GEN-END:variables
}
